export const portfolioData = {
  "events-flyer": {
    title: "Events Flyer",
    description: "Eye-catching event flyers that create buzz and drive attendance.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/2025%20Ideal%20week%20celebrations%20flyer%20NEW.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/2025%20Ideal%20week%20celebrations%20PROGRAMME%20OUTLINE.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/ALL%20WHITE%20THANKSGIVING%20PARTY%20WITH%20AMERADO.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/AMAPIANO%20MEETS%20AFROBEATS.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/Glow%20in%20the%20dark.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/Greenfield%20flyer.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/Ideal%20awards%20night%20flyer.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/NOMINEES%20FLYER%20Jude.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/NOMINEES%20FLYER%20Mike.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/Sexy%20&%20Black%20Party%20yaa.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/sip%20and%20paint%20party.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/Events_flyer/who%20wears%20the%20crown%202.jpg",
    ],
  },
  "birthday-flyers": {
    title: "Birthday Flyers",
    description: "Fun and festive birthday flyer designs perfect for celebrations.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/birthday_flyers/Awula%20Marteki%20Kodi.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/birthday_flyers/cardi%20b.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/birthday_flyers/IMG_6380.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/birthday_flyers/Maame%20Akua.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/birthday_flyers/SIS%20FLYER.jpg",
    ],
  },
  "business-flyer": {
    title: "Business Flyer",
    description: "Professional business flyers designed to promote your services and attract clients.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/a5.png",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Daniel%20Yaw.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/DeeGlitz.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/frims.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Glam%20by%20Bigail%20flyer.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Graduation%20promo.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Heackmart%20Jewelries.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Ideal%20haircut%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Josemag’s%20Hair.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Kaydef%20Farms%20eggs.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/L3F%20new.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/MAISON%20YUSIF%20FLYER.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/makeup%20packages.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Masedanie%20cosmetics.png",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Nhyiraba%20Technology.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Romay%20Nuptial%20graduate%20suits.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Sally’s%20Unique%20Touch%20classes%20black.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Silken%20scrape%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Silken%20scrape%204.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Silken%20scrape.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Special%20Touch%20Studio.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/Stella's%20beauty%20Spy.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/THE%20PRUDENT%20PHONEHUB.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/urban%20rogue.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/vacancy%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/business_flyer/vacancy.jpg",
    ],
  },
  "church-flyers": {
    title: "Church Flyers",
    description: "Professional and inspiring church flyer designs that engage and communicate your message effectively.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/Annual%20Thanksgiving%20and%20Seed%20Sowing%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/August%20Gathering%20flyer.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/fASHION%20FIESTA%20INVITATION.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/forum.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/HARVEST%20LUNCH.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/church_flyers/love%20night.jpg",
    ],
  },
  flyers: {
    title: "Flyers",
    description: "Professional business flyers designed to promote your services and attract clients.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/23b22e1fbe01e26d15691fb93203733d.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/ABIGAIL%20APURI.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/active%20parenting%20academy.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/BROCHURE%20INFRONT.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/BROCHURE.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/Dangme%20Voices.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/DONATION%20FLYER%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/Happy%20new%20year.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/IMG_8371.JPG",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/NSS%20FLYER%20new.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/OSCAR%20Yorgah%20FLYER%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/REASONS%20TO%20TAKE.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/TEAM%20PROMO.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/Team%20Rosey.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/THE%20PRUDENT%20FOUNDATION%20flyer.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/trip%20time%20with%20Hackman%20and%20friends.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/Western%20Expedition.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/flyers/WISH%20IN%20EXMAS.jpg",
    ],
  },
  logos: {
    title: "Logos",
    description: "Custom logo designs that represent your brand identity with creativity and professionalism.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/1REAL%20MUSIC.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/3fy%20logo%20green.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/15%20cliqz.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/busia%20mineral%20water%20logo%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/danok.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Fifteen%20Cliqz.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/GAATA%20RECORDS.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/k.vee%20logo.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Kwame%20Aberantie%20Studios.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/logo%205.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/LOGO%20TOOFAN%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/LuxeTrendsgh%20logo%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Masedanie%20cosmetics%20logo%202.png",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Sally’s%20lux%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Special%20Touch%20Studio%20logo%20main.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/starboba%20logo%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/Toofun%20accessories%20new%20logo.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/logos/wedding%20oasis%20logo.jpg",
    ],
  },
  "product-designs": {
    title: "Product Designs",
    description: "Innovative product design solutions that combine aesthetics with functionality.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Akumanyi%20herbal%20bitter%20mockup%20flyer%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Akumanyi%20herbal%20bitter%20mockup.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/AKUMANYI%20new%203.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Cekret%20herbal%20body%20oil%203.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Cekret%20herbal%20mixture%20jacket%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Free_Foil_Bag_Pack_PSD_Mockup.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/IMG_4571.JPG",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/IMG_4573.JPG",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Matte%20Plastic%20Jar%20Free%20Mockup_01.png",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/mockup%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/mockup%20for%20root%20b.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Nutrapeak%20pouch%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/product_designs/Nutrapeak%20pouch%202C.jpg",
    ],
  },
  "wedding-flyer": {
    title: "Wedding Flyer",
    description: "Elegant and romantic wedding flyer designs to announce your special day.",
    images: [
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/56c89df5daf711994104bb59544a3be4.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/d%20and%20e%20wedding%20save%20the%20date%203.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/d%20and%20e%20wedding%20save%20the%20date.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/Laryea%20and%20Acquah.png",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/Samuel%20&%20Jennifer%202.jpg",
      "https://cdn.jsdelivr.net/gh/iykex/ap-creative@main/images/wedding_flyer/wedding%20flyer/Solomon%20&%20Elizabeth%204.jpg",
    ],
  },
}